#!/usr/bin/env bash

# called before each command and starts stopwatch
function preexec () {
	export PREEXEC_CMD="$BASH_COMMAND"
	export PREEXEC_TIME=$(date +'%s')
}

# called after each command, stops stopwatch
# and notifies if time elpsed exceeds threshold
function precmd () {
	stop=$(date +'%s')
	start=${PREEXEC_TIME:-$stop}
	let elapsed=$stop-$start
	min=${PREEXEC_MIN:-5}

  if [ $elapsed -gt $min ]; 
  then
    if [[ -f "$blertr_bin_path/blert_now" ]]
    then
      $blertr_bin_path/blert_now "${PREEXEC_CMD:-Terminal Command}" $elapsed
    fi
  fi
}

preexec_install

